/* ═══════════════════════════════════════════════════════════
   Portfolio JS — Navigation

   The design work section is generated by build.py from projects/,
   so there is no gallery data here. Project images open full size
   from the project pages themselves.
   ═══════════════════════════════════════════════════════════ */

// ── Back to Top ────────────────────────────────────────────
const backToTop = document.getElementById('back-to-top');
window.addEventListener('scroll', () => {
  backToTop.classList.toggle('visible', window.scrollY > 400);
});
backToTop.addEventListener('click', () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
});

// ── Mobile Nav ─────────────────────────────────────────────
const mobileNavToggle = document.getElementById('mobile-nav-toggle');
const mobileNav = document.getElementById('mobile-nav');
mobileNavToggle.addEventListener('click', () => {
  mobileNavToggle.classList.toggle('active');
  mobileNav.classList.toggle('open');
});
mobileNav.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => {
    mobileNavToggle.classList.remove('active');
    mobileNav.classList.remove('open');
  });
});

// ── Scroll Reveal ──────────────────────────────────────────
const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
);

document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));

// Also reveal section headers and about text
document.querySelectorAll('.section-header, .about-text, .contact-card').forEach((el) => {
  el.classList.add('reveal');
  observer.observe(el);
});
