/* ═══════════════════════════════════════════════════════════
   Portfolio JS — Navigation

   The design work section is generated by build.py from projects/,
   so there is no gallery data here. Project images open full size
   from the project pages themselves.
   ═══════════════════════════════════════════════════════════ */

// Respects the OS setting for anything scripted. The CSS handles declarative
// motion, but scrollTo({ behavior: 'smooth' }) is invisible to a stylesheet
// and has to be opted out of here.
const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
const scrollBehavior = () => (reduceMotion.matches ? 'auto' : 'smooth');

// ── Back to Top ────────────────────────────────────────────
// Passive: this listener never calls preventDefault, and saying so lets the
// browser keep scrolling on the compositor instead of waiting on JS.
const backToTop = document.getElementById('back-to-top');
window.addEventListener(
  'scroll',
  () => {
    backToTop.classList.toggle('visible', window.scrollY > 400);
  },
  { passive: true }
);
backToTop.addEventListener('click', () => {
  window.scrollTo({ top: 0, behavior: scrollBehavior() });
});

// ── Mobile Nav ─────────────────────────────────────────────
const mobileNavToggle = document.getElementById('mobile-nav-toggle');
const mobileNav = document.getElementById('mobile-nav');

// aria-expanded is the only thing that tells assistive tech whether the menu
// is open; the class toggle is purely visual.
function setNav(open) {
  mobileNavToggle.classList.toggle('active', open);
  mobileNav.classList.toggle('open', open);
  mobileNavToggle.setAttribute('aria-expanded', String(open));
  mobileNavToggle.setAttribute(
    'aria-label',
    open ? 'Close navigation' : 'Open navigation'
  );
}

mobileNavToggle.addEventListener('click', () => {
  setNav(!mobileNav.classList.contains('open'));
});

mobileNav.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => setNav(false));
});

// Escape closes the menu and hands focus back to the button that opened it,
// matching how the lightbox on the project pages already behaves.
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && mobileNav.classList.contains('open')) {
    setNav(false);
    mobileNavToggle.focus();
  }
});

// ── Scroll Reveal ──────────────────────────────────────────
const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
);

document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));

// Also reveal section headers and about text
document.querySelectorAll('.section-header, .about-text, .contact-card').forEach((el) => {
  el.classList.add('reveal');
  observer.observe(el);
});
