/* ═══════════════════════════════════════════════════════════
   Portfolio JS — Video Showcase, Navigation

   The design work section is generated by build.py from projects/,
   so there is no gallery data here. Project images open full size
   from the project pages themselves.
   ═══════════════════════════════════════════════════════════ */

// ── Video Showcase Items (YouTube embeds) ─────────────────
const videos = [
  {
    ytId: 'gyg35mU7aus',
    title: 'The Fireside Tales — Show Opener',
    tag: 'Show Opener',
    desc: 'Full broadcast show opener with animated graphics, logos, and motion design.',
  },
  {
    ytId: 'WhIOjFfgnic',
    title: 'The Fireside Tales — Show Closer',
    tag: 'Show Closer',
    desc: 'Roll-out show closer with credits-style motion graphics and brand wrap.',
  },
  {
    ytId: 'V6cnnZgSAPk',
    title: 'Saltmarsh Legends — Show Opener',
    tag: 'Show Opener',
    desc: 'Dynamic show opener featuring custom motion graphics and brand identity.',
  },
  {
    ytId: 'yZiTWRG1apA',
    title: 'Saltmarsh Legends — Show Closer',
    tag: 'Show Closer',
    desc: 'Professional show closer with smooth transitions and branded outro.',
  },
  {
    ytId: '0giAX8tfN8o',
    title: 'Battle Arena — Logo Sting',
    tag: 'Logo Sting',
    desc: 'Animated logo reveal sting — clean, punchy, brand-forward.',
  },
  {
    ytId: 'iAQ-h9bDehc',
    title: 'Frostmaidens — Logo Sting',
    tag: 'Logo Sting',
    desc: 'Custom animated logo sting with themed visual effects and sound design.',
  },
];

// ── Helpers ───────────────────────────────────────────────
function escapeAttr(str) {
  return String(str).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function escapeHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ── Build Video Cards ──────────────────────────────────────
const videoGridEl = document.getElementById('video-grid');
videos.forEach((v) => {
  const card = document.createElement('div');
  card.className = 'video-card reveal';
  card.innerHTML = `
    <div class="video-wrapper">
      <iframe
        src="https://www.youtube.com/embed/${escapeAttr(v.ytId)}?rel=0&modestbranding=1"
        title="${escapeAttr(v.title)}"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
      ></iframe>
    </div>
    <div class="video-info">
      <span class="video-tag">${escapeHtml(v.tag)}</span>
      <h3>${escapeHtml(v.title)}</h3>
      <p>${escapeHtml(v.desc)}</p>
    </div>
  `;
  videoGridEl.appendChild(card);
});

// ── Back to Top ────────────────────────────────────────────
const backToTop = document.getElementById('back-to-top');
window.addEventListener('scroll', () => {
  backToTop.classList.toggle('visible', window.scrollY > 400);
});
backToTop.addEventListener('click', () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
});

// ── Mobile Nav ─────────────────────────────────────────────
const mobileNavToggle = document.getElementById('mobile-nav-toggle');
const mobileNav = document.getElementById('mobile-nav');
mobileNavToggle.addEventListener('click', () => {
  mobileNavToggle.classList.toggle('active');
  mobileNav.classList.toggle('open');
});
mobileNav.querySelectorAll('a').forEach((link) => {
  link.addEventListener('click', () => {
    mobileNavToggle.classList.remove('active');
    mobileNav.classList.remove('open');
  });
});

// ── Scroll Reveal ──────────────────────────────────────────
const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
);

document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));

// Also reveal section headers and about text
document.querySelectorAll('.section-header, .about-text, .contact-card').forEach((el) => {
  el.classList.add('reveal');
  observer.observe(el);
});
